In [7]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\hp\Desktop\FOOD PRODUCTION PROJECT\data\processed\crop_production_clean.csv"
)

df.head()

    Area     crop  year  Area_Harvested_ha  Production_tonnes  Yield_kg_per_ha
0  Ghana  Cassava  1961           140000.0          1050000.0           7500.0
1  Ghana    Maize  1961           237000.0           226000.0            953.6
2  Ghana     Rice  1961            27518.0            30400.0           1104.7
3  Ghana     Yams  1961           150000.0          1100000.0           7333.3
4  Ghana  Cassava  1962           140000.0          1050000.0           7500.0

In [8]:
#Create a dataset for each crop
maize = df[df["crop"] == "Maize"].copy()
cassava = df[df["crop"] == "Cassava"].copy()
rice = df[df["crop"] == "Rice"].copy()
yams = df[df["crop"] == "Yams"].copy()

In [9]:
#Sort by year
maize = maize.sort_values("year")
cassava = cassava.sort_values("year")
rice = rice.sort_values("year")
yams = yams.sort_values("year")

In [10]:
#Reset the index
maize.reset_index(drop=True, inplace=True)
cassava.reset_index(drop=True, inplace=True)
rice.reset_index(drop=True, inplace=True)
yams.reset_index(drop=True, inplace=True)

In [11]:
print("Maize:", maize.shape)
print("Cassava:", cassava.shape)
print("Rice:", rice.shape)
print("Yams:", yams.shape)

Maize: (64, 6)
Cassava: (64, 6)
Rice: (64, 6)
Yams: (64, 6)

In [12]:
for name, crop_df in {
    "Maize": maize,
    "Cassava": cassava,
    "Rice": rice,
    "Yams": yams
}.items():

    print(f"\n{name}")
    print("First year:", crop_df["year"].min())
    print("Last year :", crop_df["year"].max())
    print("Missing years:",
          crop_df["year"].diff().gt(1).sum())

Maize
First year: 1961
Last year : 2024
Missing years: 0

Cassava
First year: 1961
Last year : 2024
Missing years: 0

Rice
First year: 1961
Last year : 2024
Missing years: 0

Yams
First year: 1961
Last year : 2024
Missing years: 0

In [13]:
output_path = r"C:\Users\hp\Desktop\FOOD PRODUCTION PROJECT\data\processed"

maize.to_csv(f"{output_path}\\maize_forecast.csv", index=False)
cassava.to_csv(f"{output_path}\\cassava_forecast.csv", index=False)
rice.to_csv(f"{output_path}\\rice_forecast.csv", index=False)
yams.to_csv(f"{output_path}\\yams_forecast.csv", index=False)

In [14]:
maize.head()

    Area   crop  year  Area_Harvested_ha  Production_tonnes  Yield_kg_per_ha
0  Ghana  Maize  1961           237000.0           226000.0            953.6
1  Ghana  Maize  1962           237000.0           220000.0            928.3
2  Ghana  Maize  1963           202340.0           182889.0            903.9
3  Ghana  Maize  1964           202340.0           172728.0            853.7
4  Ghana  Maize  1965           173277.0           209001.0           1206.2